In [38]:
import pandas as pd
import os
os.chdir("F://NMIMS//sem2//ML//DATASETS FOR ML//automobile Q")
df = pd.read_csv("Automobile_data.csv")
df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...    engine-size  \
0  convertible          rwd           front        88.6  ...            130   
1  convertible          rwd           front        88.6  ...            130   
2    hatchback          rwd           front        94.5  ...            152   
3        sedan          fwd           front        99.8  ...            109   
4        sedan          4wd           front        99.4  ...            136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [39]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [40]:
#df["normalized-losses"].unique() 
df["normalized-losses"].unique() 

array(['?', '164', '158', '192', '188', '121', '98', '81', '118', '148',
       '110', '145', '137', '101', '78', '106', '85', '107', '104', '113',
       '150', '129', '115', '93', '142', '161', '153', '125', '128',
       '122', '103', '168', '108', '194', '231', '119', '154', '74',
       '186', '83', '102', '89', '87', '77', '91', '134', '65', '197',
       '90', '94', '256', '95'], dtype=object)

# clean functions (Numerical + Categorical)

In [41]:
def clean(column):
    mean=df[df[column]!="?"][column].astype(float).mean()
    df[column]=df[column].str.replace('?',str(mean)).astype(float)
    return df


In [42]:
def clean_categorical(column):
    mean = df[df[column]!="?"][column].astype(str).mode()
    df[column] = df[column].str.replace("?", str(mean)).astype(str)
    return df

In [45]:
# clean("normalized-losses")
# clean_categorical("num-of-doors")
# clean("peak-rpm")
# clean("price")
# clean("bore")
# clean("horsepower")
# #clean("stroke").head()


# Get dummies for categorical and scale them

In [46]:
import numpy as np
df=df.drop(["make"],1)
categorical=df.select_dtypes(exclude=np.number)

categorical=pd.get_dummies(categorical)
categorical.head()
y=df["price"]
df=df.drop(["price"],1)
numdf=df.select_dtypes(include=np.number)



from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
cols=list(numdf) 
numdf=scaler.fit_transform(numdf)
numdf=pd.DataFrame(numdf,columns=cols)
numdf.head()


C:\Users\sanat\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


symboling  normalized-losses  wheel-base    length     width    height  \
0        1.0           0.298429    0.058309  0.413433  0.316667  0.083333   
1        1.0           0.298429    0.058309  0.413433  0.316667  0.083333   
2        0.6           0.298429    0.230321  0.449254  0.433333  0.383333   
3        0.8           0.518325    0.384840  0.529851  0.491667  0.541667   
4        0.8           0.518325    0.373178  0.529851  0.508333  0.541667   

   curb-weight  engine-size      bore    stroke  compression-ratio  \
0     0.411171     0.260377  0.664286  0.290476             0.1250   
1     0.411171     0.260377  0.664286  0.290476             0.1250   
2     0.517843     0.343396  0.100000  0.666667             0.1250   
3     0.329325     0.181132  0.464286  0.633333             0.1875   
4     0.518231     0.283019  0.464286  0.633333             0.0625   

   horsepower  peak-rpm  city-mpg  highway-mpg  
0    0.262500  0.346939  0.222222     0.289474  
1    0.262500  0.346939  0.222222     0.289474  
2    0.441667  0.346939  0.166667     0.263158  
3    0.225000  0.551020  0.305556     0.368421  
4    0.279167  0.551020  0.138889     0.157895

In [47]:
df=pd.concat([numdf,categorical],1)
df["price"]=y

# concatinate ( numrical df and categorical)

X=df.drop(["price"],1)
y=df["price"]
X.head()

symboling  normalized-losses  wheel-base    length     width    height  \
0        1.0           0.298429    0.058309  0.413433  0.316667  0.083333   
1        1.0           0.298429    0.058309  0.413433  0.316667  0.083333   
2        0.6           0.298429    0.230321  0.449254  0.433333  0.383333   
3        0.8           0.518325    0.384840  0.529851  0.491667  0.541667   
4        0.8           0.518325    0.373178  0.529851  0.508333  0.541667   

   curb-weight  engine-size      bore    stroke        ...         \
0     0.411171     0.260377  0.664286  0.290476        ...          
1     0.411171     0.260377  0.664286  0.290476        ...          
2     0.517843     0.343396  0.100000  0.666667        ...          
3     0.329325     0.181132  0.464286  0.633333        ...          
4     0.518231     0.283019  0.464286  0.633333        ...          

   num-of-cylinders_twelve  num-of-cylinders_two  fuel-system_1bbl  \
0                        0                     0                 0   
1                        0                     0                 0   
2                        0                     0                 0   
3                        0                     0                 0   
4                        0                     0                 0   

   fuel-system_2bbl  fuel-system_4bbl  fuel-system_idi  fuel-system_mfi  \
0                 0                 0                0                0   
1                 0                 0                0                0   
2                 0                 0                0                0   
3                 0                 0                0                0   
4                 0                 0                0                0   

   fuel-system_mpfi  fuel-system_spdi  fuel-system_spfi  
0                 1                 0                 0  
1                 1                 0                 0  
2                 1                 0                 0  
3                 1                 0                 0  
4                 1                 0                 0  

[5 rows x 54 columns]

# RFE

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

#2 is features you want to take for 
features = RFE(lin_reg,5)
features.fit(X,y)
features.ranking_
features.support_
cols = list(X)
cols = pd.Series(cols)
cols[features.support_]
#selected_features=["width","curb-weight","engine-size","engine-location-front","engine-type-dohcv"]

# ttsplit

In [53]:
from sklearn.model_selection import train_test_split as tts
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=42)

# Linearv Reg

In [54]:
from sklearn.metrics import r2_score,mean_squared_error,median_absolute_error
from sklearn.linear_model import LinearRegression,RidgeCV,LassoCV,ElasticNetCV
lin_reg=LinearRegression()
lin_reg.fit(X_train,y_train)
y_pred= lin_reg.predict(X_test)
r2_score(y_test,y_pred)
#np.sqrt(mean_squared_error(y_test,y_pred))

0.8487888980319183

In [55]:
y_pred

array([28192.31664343, 19890.61968993, 10748.08020027, 12573.25190599,
       27688.02697583,  5583.12216426,  8212.84429776,  7948.35735679,
        9138.98835354,  9428.04696207, 16963.6331202 ,  7375.29939848,
       17455.79314093,  8610.76515225, 44849.61211538,  6024.05053955,
       -3201.39115315, 13666.73804523, 10947.68196337, 10408.23941416,
       11393.35488664, 17131.37677947,  5302.8561848 ,  3533.70534304,
        7834.25257756, 28691.70539216, 11757.42377943, 16508.79644631,
        4707.97117903, 17701.46822259, 27915.86563485,  6470.67772395,
        6246.08260414, 19553.66751544,  7567.56881051, 25245.42985801,
       12784.01327165, 12734.0688821 ,  7315.55496148, 14052.68101837,
        7101.4365873 ])

In [78]:
#linear regression with features 
df_main1=X[selected_features]
from sklearn.model_selection import train_test_split as tts
df_main1_train,df_main1_test,y_train,y_test=tts(df_main1,y,test_size=0.2,random_state=42)
from sklearn.metrics import r2_score,mean_squared_error,median_absolute_error
from sklearn.linear_model import LinearRegression,RidgeCV,LassoCV,ElasticNetCV
lin_reg=LinearRegression()
lin_reg.fit(df_main1_train,y_train)
y_pred= lin_reg.predict(df_main1_test)
r2_score(y_test,y_pred)
#np.sqrt(mean_squared_error(y_test,y_pred))


0.864660133426342

In [79]:
#with only numerical data
from sklearn.model_selection import train_test_split as tts
numdf_train,numdf_test,y_train,y_test=tts(numdf,y,test_size=0.2,random_state=42)
from sklearn.metrics import r2_score,mean_squared_error,median_absolute_error
from sklearn.linear_model import LinearRegression,RidgeCV,LassoCV,ElasticNetCV
lin_reg=LinearRegression()
lin_reg.fit(numdf_train,y_train)
y_pred= lin_reg.predict(numdf_test)
r2_score(y_test,y_pred)
#np.sqrt(mean_squared_error(y_test,y_pred))


0.7768763598184034

# knn 

In [80]:
#KNN
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=7)
from sklearn.model_selection import train_test_split as tts
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=42)
#KNN
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
np.sqrt(mean_squared_error(y_test,y_pred))
r2_score(y_test,y_pred)


0.7139272029581819

In [81]:
#CROSSVALIDATION
knn=KNeighborsRegressor(n_neighbors=5)
cross_val_score(knn,X,y,cv=10,scoring="r2")

array([ 0.28860077,  0.65220813,  0.81773607,  0.42080192,  0.18690768,
        0.02275941,  0.03662122, -0.27717807, -1.61062785,  0.56858243])

In [82]:
#with features 
knn.fit(df_main1_train,y_train)
y_pred=knn.predict(df_main1_test)
np.sqrt(mean_squared_error(y_test,y_pred))
r2_score(y_test,y_pred)
#y_pred

0.7250862875527313

In [125]:
#with numerical only
knn.fit(numdf_train,y_train)
y_pred=knn.predict(numdf_test)
np.sqrt(mean_squared_error(y_test,y_pred))
r2_score(y_test,y_pred)


0.6886871769078025

# Decision tree 

In [83]:
#decison tree 
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(X_train,y_train)
y_pred=dtr.predict(X_test)
dtr.score(X_test,y_test)


0.9079143604449121

In [127]:
y_pred

array([36880., 15998.,  8949., 12170., 31600.,  5118.,  5348.,  6938.,
        9295.,  7995., 15250.,  8358., 12170., 11248., 45400.,  6338.,
        5399., 12764.,  9720.,  8499., 10245., 13499.,  8058.,  5389.,
        7609., 36880.,  8449., 16515.,  7349., 15985., 31600.,  6229.,
        6918., 22018.,  8558., 31600.,  9233., 11845.,  6575., 14869.,
        6918.])

In [84]:
#decison tree with features  
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(df_main1_train, y_train)
y_pred = dtr.predict(df_main1_test) 
r2_score(y_test,y_pred)

0.8906384799317546

In [85]:
#decison tree with numerical
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(numdf_train, y_train)
y_pred = dtr.predict(numdf_test) 
r2_score(y_test,y_pred)

0.9082998833160826

# Ridge

In [86]:
#Ridge with numerical and categorical
from sklearn.linear_model import LinearRegression,RidgeCV,LassoCV,ElasticNetCV
ridge=RidgeCV(alphas=np.arange(0.1,2,0.1))
ridge.fit(X_train,y_train)
y_pred=ridge.predict(X_test)
ridge.score(X,y)

0.9113079367015655

In [135]:
y_pred

array([25926.04905134, 18999.15039064, 10334.89814527, 13296.15057927,
       25919.21206873,  6021.83390738,  6965.89687124,  8041.30530883,
        8269.32901   ,  9088.23598262, 16553.77766177,  8464.58723614,
       16644.60010367,  9223.99945095, 41526.88560958,  5827.06902572,
       -1243.08816041, 13344.22038609, 10781.89073271,  9875.5155698 ,
       11564.89435215, 17886.19699258,  7208.19999709,  2863.41165111,
        7202.56497576, 26726.25472979, 13235.69942566, 15925.47821672,
        4964.43046206, 17382.9470425 , 26739.40622619,  5970.00326199,
        6327.86355939, 21252.92859683,  7215.36142613, 25532.01988389,
       12253.6666797 , 12783.88856733,  6522.64559507, 13716.57480376,
        7107.35097198])

In [87]:
#ridge with feature 
from sklearn.linear_model import LinearRegression,RidgeCV,LassoCV,ElasticNetCV
ridge=RidgeCV(alphas=np.arange(0.1,2,0.1))
ridge.fit(df_main1_train,y_train)
y_pred=ridge.predict(df_main1_test)
ridge.score(df_main1,y)

0.9138157416301766

In [88]:
#ridge with numerical data
from sklearn.linear_model import LinearRegression,RidgeCV,LassoCV,ElasticNetCV
ridge=RidgeCV(alphas=np.arange(0.1,2,0.1))
ridge.fit(numdf_train,y_train)
y_pred=ridge.predict(numdf_test)
ridge.score(numdf,y)

0.8013368332671751